import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { motion } from "motion/react";
import { AlertCircle, Bookmark, Search, Server, Sparkles, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { z } from "zod";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { AiLoading } from "@/components/ai-loading";
import { PageHeader } from "@/components/page-shell";
import { recommend, RecommendError } from "@/lib/recommend-api";
import { CUSTOMERS, type RecommendResponse } from "@/lib/sample-data";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/_authenticated/recommend")({
  head: () => ({
    meta: [
      { title: "Recommend Products | AI Product Recommendation System" },
      {
        name: "description",
        content:
          "Enter a customer ID and let the trained neural network rank the next-best products to recommend.",
      },
      { property: "og:title", content: "Recommend Products" },
      {
        property: "og:description",
        content: "Neural product recommendations with confidence scores and reasons.",
      },
    ],
  }),
  component: RecommendPage,
});

const idSchema = z
  .string()
  .trim()
  .min(2, { message: "Enter a customer ID" })
  .max(40, { message: "Customer ID is too long" });

function RecommendPage() {
  const [customerId, setCustomerId] = useState("");
  const [topK, setTopK] = useState("6");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<RecommendResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    const parsed = idSchema.safeParse(customerId);
    if (!parsed.success) {
      toast.error(parsed.error.issues[0]?.message ?? "Invalid customer ID");
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const response = await recommend(parsed.data, Number(topK));
      setResult(response);
      if (response.source === "sample-engine") {
        toast.info("Local model service offline — using the built-in scoring engine.");
      } else {
        toast.success("Recommendations generated by your Keras model.");
      }
    } catch (err) {
      const message =
        err instanceof RecommendError
          ? err.message
          : "Could not generate recommendations for that customer.";
      setError(message);
    } finally {
      setLoading(false);
    }
  }

  async function saveAll() {
    if (!result) return;
    setSaving(true);
    const { data: userData } = await supabase.auth.getUser();
    const userId = userData.user?.id;
    if (!userId) {
      setSaving(false);
      toast.error("Your session expired. Please sign in again.");
      return;
    }
    const rows = result.recommendations.map((rec) => ({
      user_id: userId,
      customer_id: result.customer.id,
      product_code: rec.productCode,
      product_name: rec.productName,
      score: rec.score,
      confidence: rec.confidence,
      reason: rec.reason,
    }));
    const { error: insertError } = await supabase.from("saved_recommendations").insert(rows);
    setSaving(false);
    if (insertError) {
      toast.error("Could not save these recommendations.");
      return;
    }
    toast.success(`Saved ${rows.length} recommendations to your reports.`);
  }

  return (
    <div>
      <PageHeader
        title="Recommend Products"
        description="Enter a customer ID to score every unseen product with the trained ANN and rank the best matches."
      />

      <form onSubmit={handleSubmit} className="glass rounded-2xl p-5">
        <div className="grid gap-4 sm:grid-cols-[1fr_auto_auto] sm:items-end">
          <div className="space-y-2">
            <Label htmlFor="customerId">Customer ID</Label>
            <div className="relative">
              <Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                id="customerId"
                value={customerId}
                onChange={(e) => setCustomerId(e.target.value)}
                placeholder="e.g. 12437"
                maxLength={40}
                className="pl-9"
                list="customer-suggestions"
                required
              />
              <datalist id="customer-suggestions">
                {CUSTOMERS.map((c) => (
                  <option key={c.id} value={c.id}>
                    {c.name}
                  </option>
                ))}
              </datalist>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="topK">Results</Label>
            <Select value={topK} onValueChange={setTopK}>
              <SelectTrigger id="topK" className="w-full sm:w-28">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {["3", "6", "9", "12"].map((n) => (
                  <SelectItem key={n} value={n}>
                    Top {n}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <Button
            type="submit"
            disabled={loading}
            className="gradient-brand border-0 text-primary-foreground"
          >
            <Sparkles className="mr-1.5 size-4" />
            Get Recommendations
          </Button>
        </div>

        <div className="mt-4 flex flex-wrap gap-2">
          <span className="text-xs text-muted-foreground">Try:</span>
          {CUSTOMERS.slice(0, 6).map((c) => (
            <button
              key={c.id}
              type="button"
              onClick={() => setCustomerId(c.id)}
              className="rounded-full border border-border/70 px-3 py-1 text-xs transition-colors hover:bg-accent"
            >
              {c.id}
            </button>
          ))}
        </div>
      </form>

      {loading && (
        <div className="mt-6">
          <AiLoading />
        </div>
      )}

      {error && !loading && (
        <Alert variant="destructive" className="mt-6">
          <AlertCircle className="size-4" />
          <AlertTitle>No recommendations</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {result && !loading && (
        <div className="mt-8">
          <div className="glass flex flex-wrap items-center justify-between gap-4 rounded-2xl p-5">
            <div>
              <p className="text-xs tracking-wide text-muted-foreground uppercase">Customer</p>
              <h2 className="mt-1 font-display text-xl font-bold">
                {result.customer.name} · {result.customer.id}
              </h2>
              <p className="mt-1 text-sm text-muted-foreground">
                {result.customer.totalOrders} orders · ₹{result.customer.totalSpend.toLocaleString()}{" "}
                lifetime value · {result.customer.country}
              </p>
            </div>
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant={result.source === "flask-model" ? "default" : "secondary"}>
                <Server className="mr-1 size-3" />
                {result.source === "flask-model" ? "Keras model" : "Built-in engine"}
              </Badge>
              <Badge variant="outline">{result.elapsedMs} ms</Badge>
              <Button onClick={saveAll} disabled={saving} variant="outline" size="sm">
                <Bookmark className="mr-1.5 size-4" />
                Save all
              </Button>
            </div>
          </div>

          <div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {result.recommendations.map((rec, i) => (
              <motion.article
                key={rec.productCode}
                initial={{ opacity: 0, y: 18 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: i * 0.07 }}
                className="glass glass-hover flex flex-col rounded-2xl p-5"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <Badge variant="secondary" className="text-xs">
                      #{i + 1} · {rec.category}
                    </Badge>
                    <h3 className="mt-3 font-display text-base leading-snug font-semibold">
                      {rec.productName}
                    </h3>
                    <p className="mt-1 text-xs text-muted-foreground">Code {rec.productCode}</p>
                  </div>
                  <span className="gradient-text font-display text-2xl font-bold">
                    {rec.confidence.toFixed(1)}%
                  </span>
                </div>

                <div className="mt-4">
                  <Progress value={rec.confidence} className="h-1.5" />
                  <p className="mt-2 flex items-center gap-1.5 text-xs text-muted-foreground">
                    <TrendingUp className="size-3.5" /> Affinity score {rec.score.toFixed(4)}
                  </p>
                </div>

                <p className="mt-4 text-sm text-muted-foreground">{rec.reason}</p>
              </motion.article>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
